---
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-service
  labels:
    app: sampleapp-nginx-app-deployment
spec:
  type:
  selector:
    app: sampleapp-nginx-app-deployment
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-nginx-app-deployment
  labels:
    app: sampleapp-nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleapp-nginx-app
  template:
    metadata:
      labels:
        app: sampleapp-nginx-app
    spec:
      containers:
        - name: sampleapp-nginx-app
          image: stacksimplify/kube-nginxapp1:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: sample-pv
              mountPath: "/usr/share/nginx/html/app1"
      volumes:
        - name: sample-pv
          persistentVolumeClaim:
            claimName: sampleapp-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sampleapp-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sampleapp-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
